'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace ControlOriginsWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DataAnalysisSoap", [Namespace]:="http://ws.controlorigins.com/")>  _
    Partial Public Class DataAnalysis
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetSurveyResponseSummaryGridOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSurveyResponseGroupGridOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSurveyResponseAnswersGridOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetApplicationGridOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSurveySummaryGridOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetQuestionListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.DataGridVisualization.My.MySettings.Default.DataGridVisualization_ControlOriginsWS_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetSurveyResponseSummaryGridCompleted As GetSurveyResponseSummaryGridCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSurveyResponseGroupGridCompleted As GetSurveyResponseGroupGridCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSurveyResponseAnswersGridCompleted As GetSurveyResponseAnswersGridCompletedEventHandler
        
        '''<remarks/>
        Public Event GetApplicationGridCompleted As GetApplicationGridCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSurveySummaryGridCompleted As GetSurveySummaryGridCompletedEventHandler
        
        '''<remarks/>
        Public Event GetQuestionListCompleted As GetQuestionListCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.controlorigins.com/GetSurveyResponseSummaryGrid", RequestNamespace:="http://ws.controlorigins.com/", ResponseNamespace:="http://ws.controlorigins.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSurveyResponseSummaryGrid(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid) As CO_DataGrid
            Dim results() As Object = Me.Invoke("GetSurveyResponseSummaryGrid", New Object() {Filters, myGuid})
            Return CType(results(0),CO_DataGrid)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSurveyResponseSummaryGridAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid)
            Me.GetSurveyResponseSummaryGridAsync(Filters, myGuid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSurveyResponseSummaryGridAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid, ByVal userState As Object)
            If (Me.GetSurveyResponseSummaryGridOperationCompleted Is Nothing) Then
                Me.GetSurveyResponseSummaryGridOperationCompleted = AddressOf Me.OnGetSurveyResponseSummaryGridOperationCompleted
            End If
            Me.InvokeAsync("GetSurveyResponseSummaryGrid", New Object() {Filters, myGuid}, Me.GetSurveyResponseSummaryGridOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSurveyResponseSummaryGridOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSurveyResponseSummaryGridCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSurveyResponseSummaryGridCompleted(Me, New GetSurveyResponseSummaryGridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.controlorigins.com/GetSurveyResponseGroupGrid", RequestNamespace:="http://ws.controlorigins.com/", ResponseNamespace:="http://ws.controlorigins.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSurveyResponseGroupGrid(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid) As CO_DataGrid
            Dim results() As Object = Me.Invoke("GetSurveyResponseGroupGrid", New Object() {Filters, myGuid})
            Return CType(results(0),CO_DataGrid)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSurveyResponseGroupGridAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid)
            Me.GetSurveyResponseGroupGridAsync(Filters, myGuid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSurveyResponseGroupGridAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid, ByVal userState As Object)
            If (Me.GetSurveyResponseGroupGridOperationCompleted Is Nothing) Then
                Me.GetSurveyResponseGroupGridOperationCompleted = AddressOf Me.OnGetSurveyResponseGroupGridOperationCompleted
            End If
            Me.InvokeAsync("GetSurveyResponseGroupGrid", New Object() {Filters, myGuid}, Me.GetSurveyResponseGroupGridOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSurveyResponseGroupGridOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSurveyResponseGroupGridCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSurveyResponseGroupGridCompleted(Me, New GetSurveyResponseGroupGridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.controlorigins.com/GetSurveyResponseAnswersGrid", RequestNamespace:="http://ws.controlorigins.com/", ResponseNamespace:="http://ws.controlorigins.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSurveyResponseAnswersGrid(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid) As CO_DataGrid
            Dim results() As Object = Me.Invoke("GetSurveyResponseAnswersGrid", New Object() {Filters, myGuid})
            Return CType(results(0),CO_DataGrid)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSurveyResponseAnswersGridAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid)
            Me.GetSurveyResponseAnswersGridAsync(Filters, myGuid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSurveyResponseAnswersGridAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid, ByVal userState As Object)
            If (Me.GetSurveyResponseAnswersGridOperationCompleted Is Nothing) Then
                Me.GetSurveyResponseAnswersGridOperationCompleted = AddressOf Me.OnGetSurveyResponseAnswersGridOperationCompleted
            End If
            Me.InvokeAsync("GetSurveyResponseAnswersGrid", New Object() {Filters, myGuid}, Me.GetSurveyResponseAnswersGridOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSurveyResponseAnswersGridOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSurveyResponseAnswersGridCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSurveyResponseAnswersGridCompleted(Me, New GetSurveyResponseAnswersGridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.controlorigins.com/GetApplicationGrid", RequestNamespace:="http://ws.controlorigins.com/", ResponseNamespace:="http://ws.controlorigins.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetApplicationGrid(ByVal myGUID As System.Guid) As CO_DataGrid
            Dim results() As Object = Me.Invoke("GetApplicationGrid", New Object() {myGUID})
            Return CType(results(0),CO_DataGrid)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetApplicationGridAsync(ByVal myGUID As System.Guid)
            Me.GetApplicationGridAsync(myGUID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetApplicationGridAsync(ByVal myGUID As System.Guid, ByVal userState As Object)
            If (Me.GetApplicationGridOperationCompleted Is Nothing) Then
                Me.GetApplicationGridOperationCompleted = AddressOf Me.OnGetApplicationGridOperationCompleted
            End If
            Me.InvokeAsync("GetApplicationGrid", New Object() {myGUID}, Me.GetApplicationGridOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetApplicationGridOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetApplicationGridCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetApplicationGridCompleted(Me, New GetApplicationGridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.controlorigins.com/GetSurveySummaryGrid", RequestNamespace:="http://ws.controlorigins.com/", ResponseNamespace:="http://ws.controlorigins.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSurveySummaryGrid(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid) As CO_DataGrid
            Dim results() As Object = Me.Invoke("GetSurveySummaryGrid", New Object() {Filters, myGuid})
            Return CType(results(0),CO_DataGrid)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSurveySummaryGridAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid)
            Me.GetSurveySummaryGridAsync(Filters, myGuid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSurveySummaryGridAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid, ByVal userState As Object)
            If (Me.GetSurveySummaryGridOperationCompleted Is Nothing) Then
                Me.GetSurveySummaryGridOperationCompleted = AddressOf Me.OnGetSurveySummaryGridOperationCompleted
            End If
            Me.InvokeAsync("GetSurveySummaryGrid", New Object() {Filters, myGuid}, Me.GetSurveySummaryGridOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSurveySummaryGridOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSurveySummaryGridCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSurveySummaryGridCompleted(Me, New GetSurveySummaryGridCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.controlorigins.com/GetQuestionList", RequestNamespace:="http://ws.controlorigins.com/", ResponseNamespace:="http://ws.controlorigins.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetQuestionList(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid) As CO_DataGrid
            Dim results() As Object = Me.Invoke("GetQuestionList", New Object() {Filters, myGuid})
            Return CType(results(0),CO_DataGrid)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetQuestionListAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid)
            Me.GetQuestionListAsync(Filters, myGuid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetQuestionListAsync(ByVal Filters() As SQLFilterClause, ByVal myGuid As System.Guid, ByVal userState As Object)
            If (Me.GetQuestionListOperationCompleted Is Nothing) Then
                Me.GetQuestionListOperationCompleted = AddressOf Me.OnGetQuestionListOperationCompleted
            End If
            Me.InvokeAsync("GetQuestionList", New Object() {Filters, myGuid}, Me.GetQuestionListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetQuestionListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetQuestionListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetQuestionListCompleted(Me, New GetQuestionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.controlorigins.com/")>  _
    Partial Public Class SQLFilterClause
        
        Private fieldField As String
        
        Private fieldOperatorField As SQLFilterOperator
        
        Private conjunctionField As SQLFilterConjunction
        
        Private fieldTypeField As String
        
        Private argumentField As String
        
        '''<remarks/>
        Public Property Field() As String
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldOperator() As SQLFilterOperator
            Get
                Return Me.fieldOperatorField
            End Get
            Set
                Me.fieldOperatorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Conjunction() As SQLFilterConjunction
            Get
                Return Me.conjunctionField
            End Get
            Set
                Me.conjunctionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldType() As String
            Get
                Return Me.fieldTypeField
            End Get
            Set
                Me.fieldTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Argument() As String
            Get
                Return Me.argumentField
            End Get
            Set
                Me.argumentField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.controlorigins.com/")>  _
    Public Enum SQLFilterOperator
        
        '''<remarks/>
        Equal
        
        '''<remarks/>
        NotEqual
        
        '''<remarks/>
        GreaterThan
        
        '''<remarks/>
        LessThan
        
        '''<remarks/>
        GreaterThanEqual
        
        '''<remarks/>
        LessThanEqual
        
        '''<remarks/>
        dbLike
        
        '''<remarks/>
        dbIn
        
        '''<remarks/>
        dbBetween
        
        '''<remarks/>
        dbIsNull
        
        '''<remarks/>
        dbIsNotNull
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.controlorigins.com/")>  _
    Public Enum SQLFilterConjunction
        
        '''<remarks/>
        andConjunction
        
        '''<remarks/>
        orConjunction
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.controlorigins.com/")>  _
    Partial Public Class GridRow
        
        Private nameField As String
        
        Private valueField() As String
        
        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As String()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.controlorigins.com/")>  _
    Partial Public Class GridColumn
        
        Private dataTypeField As String
        
        Private columnDisplayFormatField As DisplayFormat
        
        Private displayNameField As String
        
        Private sourceNameField As String
        
        Private indexField As Integer
        
        Private minValueField As String
        
        Private maxValueField As String
        
        Private uniqueValuesField As Integer
        
        Private mostCommonField As String
        
        Private leastCommonField As String
        
        Private columnValuesField() As String
        
        '''<remarks/>
        Public Property DataType() As String
            Get
                Return Me.dataTypeField
            End Get
            Set
                Me.dataTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ColumnDisplayFormat() As DisplayFormat
            Get
                Return Me.columnDisplayFormatField
            End Get
            Set
                Me.columnDisplayFormatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayName() As String
            Get
                Return Me.displayNameField
            End Get
            Set
                Me.displayNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SourceName() As String
            Get
                Return Me.sourceNameField
            End Get
            Set
                Me.sourceNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Index() As Integer
            Get
                Return Me.indexField
            End Get
            Set
                Me.indexField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MinValue() As String
            Get
                Return Me.minValueField
            End Get
            Set
                Me.minValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MaxValue() As String
            Get
                Return Me.maxValueField
            End Get
            Set
                Me.maxValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UniqueValues() As Integer
            Get
                Return Me.uniqueValuesField
            End Get
            Set
                Me.uniqueValuesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MostCommon() As String
            Get
                Return Me.mostCommonField
            End Get
            Set
                Me.mostCommonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LeastCommon() As String
            Get
                Return Me.leastCommonField
            End Get
            Set
                Me.leastCommonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ColumnValues() As String()
            Get
                Return Me.columnValuesField
            End Get
            Set
                Me.columnValuesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.controlorigins.com/")>  _
    Public Enum DisplayFormat
        
        '''<remarks/>
        Number
        
        '''<remarks/>
        Currency
        
        '''<remarks/>
        Text
        
        '''<remarks/>
        Percent
        
        '''<remarks/>
        Float
        
        '''<remarks/>
        Thumbnail
        
        '''<remarks/>
        Hidden
        
        '''<remarks/>
        ShortDate
        
        '''<remarks/>
        LongDate
        
        '''<remarks/>
        Link
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.controlorigins.com/")>  _
    Partial Public Class CO_DataGrid
        
        Private titleField As String
        
        Private gridColumnsField() As GridColumn
        
        Private gridRowsField() As GridRow
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GridColumns() As GridColumn()
            Get
                Return Me.gridColumnsField
            End Get
            Set
                Me.gridColumnsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GridRows() As GridRow()
            Get
                Return Me.gridRowsField
            End Get
            Set
                Me.gridRowsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetSurveyResponseSummaryGridCompletedEventHandler(ByVal sender As Object, ByVal e As GetSurveyResponseSummaryGridCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSurveyResponseSummaryGridCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CO_DataGrid
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CO_DataGrid)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetSurveyResponseGroupGridCompletedEventHandler(ByVal sender As Object, ByVal e As GetSurveyResponseGroupGridCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSurveyResponseGroupGridCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CO_DataGrid
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CO_DataGrid)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetSurveyResponseAnswersGridCompletedEventHandler(ByVal sender As Object, ByVal e As GetSurveyResponseAnswersGridCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSurveyResponseAnswersGridCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CO_DataGrid
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CO_DataGrid)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetApplicationGridCompletedEventHandler(ByVal sender As Object, ByVal e As GetApplicationGridCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetApplicationGridCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CO_DataGrid
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CO_DataGrid)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetSurveySummaryGridCompletedEventHandler(ByVal sender As Object, ByVal e As GetSurveySummaryGridCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSurveySummaryGridCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CO_DataGrid
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CO_DataGrid)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GetQuestionListCompletedEventHandler(ByVal sender As Object, ByVal e As GetQuestionListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetQuestionListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CO_DataGrid
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CO_DataGrid)
            End Get
        End Property
    End Class
End Namespace
